sf:
  user: "![iZaKpY+mVp+Q9xHgfrPPmhAtIUe726XV]"
  pass: "![hKwf6mtblooOgPbvqNSMaYosYHTodJ2d]"
  token: "![EugRPoMZsN+lr9STA7hda2kqamF0dMaeWloG3dDqOXU=]"


  
keystore:
  path: "![921Q1gGUoHvtMWXZ2hdwmiCBx3ZXxIrx]"
  password: "![SPkL/l1MAi8UidhpyLaVHA==]"
  keyPassword: "![SPkL/l1MAi8UidhpyLaVHA==]"  
