#%RAML 1.0 Library
types:
  delete_response:
    properties:
      is_success:
        description: Success
        type: boolean
        required: true
      response:
        type: array
        items:
          type: object
          properties:
            payload:
              type: object
              properties:
                success: boolean
                id: string
                errors: array 
      