#%RAML 1.0 Library
types:
  get_all_response:
    description: retreiving all objects
    type: array
    items:
      properties:
        name:
          type: string
          required: false
        dateOfBirth__c:
          type: string
          required: true
        gender__c:
          type: string
          required: true
        email__c:
          type: string
          required: true
        phone__c:
          type: string
          required: true
        address__c:
          type: string
          required: true
        