#%RAML 1.0 Library
types:
  post_request:
    description: creating new object
    type: object
    properties:
      name:
        type: string
        required: false
      dateOfBirth__c:
        type: string
        required: true
      gender__c:
        type: string
        required: true
      email__c:
        type: string
        required: true
      phone__c:
        type: string
        required: true
      address__c:
        type: string
        required: true  

  post_response:
    description: Pick Release Response
    properties:
      is_success :
        type: boolean
        required: true
      errors:
        type: array
        required: false
        items:
          properties:
            error_code:
              type: string
              required: false
            error_message:
              type: string
              required: false       